SELECT COUNT(1) FROM(SELECT 
-- id
ADJUDICACION.NUMERO_CONTRATO AS id_contract,
-- awardID
ADJUDICACION.ID_ADJUDICACION AS awardID,
-- status
  CASE PROCESO.ESTADO_PROCESO
    WHEN '3' THEN 'pending'
    WHEN '4' THEN 'active'
    WHEN '5' THEN 'terminated'
    WHEN '7' THEN 'cancelled'
    WHEN '8' THEN 'terminated'
    ELSE NULL
END status,

-- period
-- period - startDate
  ADJUDICACION.FECHA_INICIO_EJECUCION AS startDate,
-- period - endDate
  CASE ADJUDICACION.RANGO_PLAZO_EJECUCION
    WHEN 'M'
      THEN
        ADD_MONTHS(ADJUDICACION.fecha_inicio_ejecucion, NVL(ADJUDICACION.plazo_ejecucion, 0))
    WHEN 'D'
      THEN
        ADJUDICACION.fecha_inicio_ejecucion + NVL(ADJUDICACION.plazo_ejecucion, 0)
    ELSE NULL
  END endDate,

-- value
-- value - amount
  ADJUDICACION.VALOR_CONTRATO AS amount,
-- value - currency
  CASE ADJUDICACION.ID_MONEDA_PAGO 
    WHEN '1' THEN 'COP'
    WHEN '2' THEN 'USD'
    WHEN '4' THEN 'EUR'
    WHEN '5' THEN 'GBP'
    WHEN '6' THEN 'AFN'
    WHEN '10' THEN 'VEF'
    WHEN '11' THEN 'BOB'
    WHEN '20' THEN 'CZK'
    ELSE NULL
  END currency,

-- Items
-- Items - id
  CASE 
    WHEN PROCESO.UNSPSC_CLASE IS NULL THEN PROCESO.ID_OBJETO_CONTRATO
    ELSE PROCESO.UNSPSC_CLASE
  END item_id,
-- Items - description
  CASE 
    WHEN PROCESO.UNSPSC_CLASE IS NULL THEN OBJETO.DESC_OBJE
    ELSE ITEM.NOM_CLASE
  END item_description,
-- Item _ Classification  
-- Item _ Classification - scheme
  'UNSPSC' AS item_classi_scheme,
-- Item _ Classification - id
  CASE 
    WHEN PROCESO.UNSPSC_CLASE IS NULL THEN PROCESO.ID_OBJETO_CONTRATO
    ELSE PROCESO.UNSPSC_CLASE
  END item_classi_id, 
-- Item _ Classification - description
  CASE 
    WHEN PROCESO.UNSPSC_CLASE IS NULL THEN OBJETO.DESC_OBJE
    ELSE ITEM.NOM_CLASE
  END item_classi_description,
-- Item _ Classification - uri
  'http://www.colombiacompra.gov.co/es/clasificacion' AS item_classi_uri,

-- dateSigned
ADJUDICACION.FECHA_FIRMA_CONTRATO AS dateSigned,

-- amendment
  MODIFICACIONES.FECHA_MODIFICACION AS amendment_date,
-- amendment _ changes
-- amendment _ changes - property
  MODIFICACIONES.CAMPO AS amendment_changes_property,
-- amendment _ changes - former_value
  MODIFICACIONES.VALOR_ANTERIOR AS amendment_changes_former_value,
-- amendment - rationale
  MODIFICACIONES.COMENTARIOS AS amendment_rationale,
  
  PROCESO.NUM_CONSTANCIA AS num_constancia 
FROM T_PTC_ADJUDICACIONES ADJUDICACION
LEFT JOIN T_PTC_PROCESOS PROCESO
  ON ADJUDICACION.ID_PROCESO = PROCESO.NUM_CONSTANCIA
LEFT JOIN TB_USUARIOLDAP USRLDAP
  ON PROCESO.USUARIO = USRLDAP.USUARIO
LEFT JOIN T_PTC_TIPOS_DOCUMENTOS TIPODOC
  ON TIPODOC.IDENTIFICACION = ADJUDICACION.TIPO_DOC_CONTRATISTA
LEFT JOIN T_PTC_UBICACIONES_GEO GEO
  ON ADJUDICACION.ID_MUNICIPIO_CONTRATISTA = GEO.IDENTIFICADOR
LEFT JOIN UNSPSC_CLASES ITEM
  ON PROCESO.UNSPSC_CLASE = ITEM.COD_CLASE
LEFT JOIN TPOR_OBJE OBJETO
  ON PROCESO.ID_OBJETO_CONTRATO = OBJETO.CODI_OBJE
LEFT JOIN (
  SELECT 
    SOPORTES_MODIFICACIONES.FECHA_MODIFICACION,
    SOPORTES_MODIFICACIONES.CAMPO,
    SOPORTES_MODIFICACIONES.VALOR_ANTERIOR,
    SOPORTES_MODIFICACIONES.COMENTARIOS,
    SOPORTES_MODIFICACIONES.ID_ADJUDICACION
  FROM T_PTC_SOPORTES_MODIFICACIONES SOPORTES_MODIFICACIONES
  WHERE 
    SOPORTES_MODIFICACIONES.ID_ADJUDICACION IS NOT NULL
    AND SOPORTES_MODIFICACIONES.ID_ADJUDICACION != 0
    AND 
      SOPORTES_MODIFICACIONES.ID_ADJUDICACION IN (SELECT MAX(SOPOR.ID_ADJUDICACION) FROM T_PTC_SOPORTES_MODIFICACIONES SOPOR GROUP BY SOPOR.ID_ADJUDICACION)
  ) MODIFICACIONES
  ON ADJUDICACION.ID_ADJUDICACION = MODIFICACIONES.ID_ADJUDICACION
WHERE 
  USRLDAP.IDENTIDAD <> '199999999'
  AND TRUNC(PROCESO.FECHA_CARGUE) BETWEEN TO_DATE('01/01/2015','DD/MM/YYYY') AND TO_DATE('19/08/2015','DD/MM/YYYY'))
;