SELECT 
MUNICIPIO.DESCRIPCION AS locality,
DEPARTAMENTO.DESCRIPCION AS region,
'Colombia' AS countryName,
DPTOEJE.ID_PROCESO
FROM T_PTC_DPTOS_EJECUCION DPTOEJE
LEFT JOIN T_PTC_UBICACIONES_GEO MUNICIPIO
  ON DPTOEJE.ID_DEPARTAMENTO = MUNICIPIO.IDENTIFICADOR
LEFT JOIN T_PTC_UBICACIONES_GEO DEPARTAMENTO
  ON MUNICIPIO.IDENTIFICADOR_PADRE = DEPARTAMENTO.IDENTIFICADOR
LEFT JOIN T_PTC_PROCESOS PROCESO
  ON DPTOEJE.ID_PROCESO = PROCESO.NUM_CONSTANCIA
LEFT JOIN TB_USUARIOLDAP USRLDAP
  ON PROCESO.USUARIO = USRLDAP.USUARIO
WHERE 
  TRUNC(PROCESO.FECHA_CARGUE) BETWEEN TO_DATE('01/01/2015','DD/MM/YYYY') AND TO_DATE('01/01/2015','DD/MM/YYYY')
  AND USRLDAP.IDENTIDAD <> '199999999';