SELECT 
NOVEDAD.OID AS id,
TIPO.DESCRIPCION AS title,
TIPO.EXPLICACION AS description,
NOVEDAD.FECHA_NOVEDAD AS dueDate,
NOVEDAD.NUMERO_CONSTANCIA AS num_constancia
FROM T_PTC_NOVEDADES NOVEDAD
INNER JOIN T_PTC_TIPO_NOVEDAD TIPO
  ON NOVEDAD.OID_TIPO_NOVEDAD = TIPO.OID
LEFT JOIN T_PTC_PROCESOS PROCESO
  ON NOVEDAD.NUMERO_CONSTANCIA = PROCESO.NUM_CONSTANCIA
LEFT JOIN TB_USUARIOLDAP USRLDAP
  ON PROCESO.USUARIO = USRLDAP.USUARIO
WHERE
  TRUNC(PROCESO.FECHA_CARGUE) BETWEEN TO_DATE('01/01/2015','DD/MM/YYYY') AND TO_DATE('31/01/2015','DD/MM/YYYY')
AND USRLDAP.IDENTIDAD <> '199999999'
AND OID_ADJUDICACION IS NULL;
